### ISSUE TITLE
Out-of-bounds memory access runtime error found in `std::array<float, 4> getOriginBox(const std::array<float, 4> &box, ...)`

### ISSUE THREAD

**Issue by Arpan3323** [nndeploy/nndeploy#102]
Hi, I have found an out-of-bounds access error in the function linked below. The error occurs at **line 28** when trying to access `box[4]` (fifth element) because `box` can only contain four elements at max. 
https://github.com/nndeploy/nndeploy/blob/5f57d2d19000fcdf62569d62739c49906863146f/plugin/source/nndeploy/detect/util.cc#L20-L31

### Example (to reproduce error)

```C++
extern "C" int LLVMFuzzerTestOneInput(uint8_t *Data, size_t Size)
{
    if (Size < 20) {return 0;}
    float *fuzzedInp = reinterpret_cast<float*>(Data);
    std::array<float, 4> mBox = {fuzzedInp[0], fuzzedInp[1], fuzzedInp[2], fuzzedInp[3]};
    float mXOffset = fuzzedInp[4];
    float mYOffset = fuzzedInp[4] * 0.4;
    int mHeight = Size * 0.5;
    int mWidth = Size * 0.8;
    getOriginBox(mBox,fuzzedInp,mXOffset,mYOffset,mWidth,mHeight);
    return 0;
}
```

### Crash report
```
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2366642635
INFO: Loaded 1 modules   (57 inline 8-bit counters): 57 [0x555fe3b400a0, 0x555fe3b400d9), 
INFO: Loaded 1 PC tables (57 PCs): 57 [0x555fe3b400e0,0x555fe3b40470), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED cov: 2 ft: 2 corp: 1/1b exec/s: 0 rss: 33Mb
=================================================================
==43861==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f2a3c11c3b0 at pc 0x555fe3af8ab8 bp 0x7ffc2070b180 sp 0x7ffc2070b178
READ of size 4 at 0x7f2a3c11c3b0 thread T0
    #0 0x555fe3af8ab7 in getOriginBox(std::array<float, 4ul> const&, float const*, float, float, int, int) fuzzer.cpp:16:25
    #1 0x555fe3af8f6a in LLVMFuzzerTestOneInput fuzzer.cpp:30:5
    #2 0x555fe3a03c54 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (utilFuzzer_getOriginBox+0x4dc54) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)
    #3 0x555fe3a03349 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (utilFuzzer_getOriginBox+0x4d349) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)
    #4 0x555fe3a04b35 in fuzzer::Fuzzer::MutateAndTestOne() (utilFuzzer_getOriginBox+0x4eb35) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)
    #5 0x555fe3a05695 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (utilFuzzer_getOriginBox+0x4f695) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)
    #6 0x555fe39f296f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (utilFuzzer_getOriginBox+0x3c96f) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)
    #7 0x555fe3a1cff6 in main (utilFuzzer_getOriginBox+0x66ff6) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)
    #8 0x7f2a3df651c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #9 0x7f2a3df6528a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #10 0x555fe39e7954 in _start (utilFuzzer_getOriginBox+0x31954) (BuildId: d41ba62ddaf45703cff6299eb93f316ba272a94a)

Address 0x7f2a3c11c3b0 is located in stack of thread T0 at offset 48 in frame
    #0 0x555fe3af8c07 in LLVMFuzzerTestOneInput fuzzer.cpp:22

  This frame has 1 object(s):
    [32, 48) 'mBox' (line 25) <== Memory access at offset 48 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow fuzzer.cpp:16:25 in getOriginBox(std::array<float, 4ul> const&, float const*, float, float, int, int)
Shadow bytes around the buggy address:
  0x7f2a3c11c100: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a3c11c180: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a3c11c200: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a3c11c280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f2a3c11c300: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x7f2a3c11c380: f1 f1 f1 f1 00 00[f3]f3 00 00 00 00 00 00 00 00
  0x7f2a3c11c400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a3c11c480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a3c11c500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a3c11c580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f2a3c11c600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==43861==ABORTING
```

### Potential fix
My hunch is that this is how `float xmax` and `float ymax` should be computed:
```C++
std::array<float, 4> getOriginBox(const std::array<float, 4> &box,
                                  const float *scale_factor, float x_offset,
                                  float y_offset, int ori_width,
                                  int ori_height) {
  float xmin = std::max(box[0] / scale_factor[0] + x_offset, 0.f);
  float ymin = std::max(box[1] / scale_factor[1] + y_offset, 0.f);
  //use box[2] instead of box[3]
  float xmax = std::min(box[2] / scale_factor[2] + x_offset,
                        static_cast<float>(ori_width) - 1.f);
  //use box[3] instead of box[4]
  float ymax = std::min(box[3] / scale_factor[3] + y_offset,
                        static_cast<float>(ori_height) - 1.f);
  return {xmin, ymin, xmax, ymax};
}
```
But I could be wrong since I am only guessing what the correct computation should be.

Please let me know if you have any questions :)

Sincerely,
Arpan Srivastava

**Comment by Alwaysssssss** [comment]
Thank you for pointing out the mistake. Your understanding is correct: the implementation of the getOriginBox function was incorrect, and your subsequent implementation is correct. Could you please submit a pull request (PR) to fix this bug?

**Comment by Arpan3323** [comment]
Done. Please feel free to make suggestions if you have any.

**Comment by Alwaysssssss** [comment]
Thank you very much for your contributions to our project, especially for the issues and pull requests (PRs) you've raised. Your issues are well-organized and well-substantiated. We are eagerly looking forward to your continued active participation in our project to jointly advance its development.
